### ISSUE TITLE
A proper Github organization / join cl-cookbook?

### ISSUE THREAD

**Issue by vindarel** [cl-library-docs/common-lisp-libraries#5]
Hello,

this project is already helpful and could become a reference. Then,

What if you created a Github organization for this project? 

Alternatively, what if you moved it to the cl-cookbook organization? The documentation would be published on an URL like `https://lispcookbook.github.io/common-lisp.readthedocs`. The rationale is to have documentation-related efforts under the same umbrella. There's a little mismatch between "cookbook" and "readthedocs" though.

**Comment by digikar99** [comment]
Can agree. However, can all of these be coordinated with [common-lisp.net](https://common-lisp.net/) as well? Or does it save on funds (or perhaps, makes contributions and all easier/friendlier to new people) to keep things on github?

Edit: link to common-lisp.net

**Comment by digikar99** [comment]
I'll go with the hunch that it'd make contributions easier for new people by keeping things on github. 

I could very well just move it to cl-cookbook org; perhaps, renaming it to cl-rtd? (I'd welcome suggestions for the name - cl-library-docs? readthedocs would just be the "frontend".) The goals aren't too different, especially with the "getting started" sections.

**Comment by vindarel** [comment]
> it'd make contributions easier for new people by keeping things on github.

\+ 1000 Possibly the common-lisp.net could create a subdomain that points to your repo. I also highly prefer this to be on an easily accessible repository.

cl-rtd is short and nice

I like cl-readthedocs too, explicit is nice (btw, isn't it possible to send the documentation to the real readthedocs website?)

RTLD ? aka Read The Lisp Doc, similar to TLDR;

**Comment by digikar99** [comment]
> btw, isn't it possible to send the documentation to the real readthedocs website?

Yup, I tinkered around with the idea today, it seems the subdomain is "subdomain-ifed" from the repository name, so the current name is a bad choice, may be something like "lisp-libraries", "cl-libraries", "cl-library-docs", or any other suggestions? Docs would be implicity in the ".readthedocs.io" part, so, if I had to choose, it'd be "cl-libraries", since lisp refers to the lisp family outside the common lisp community.

**Comment by digikar99** [comment]
Okay, done. 

The site is also up at [common-lisp-libraries.readthedocs.io](https://common-lisp-libraries.readthedocs.io/) or [common-lisp-libraries.rtfd.io](https://common-lisp-libraries.rtfd.io/).
