### ISSUE TITLE
Quicklisp 'Getting Started' link broken

### ISSUE THREAD

**Issue by Zulu-Inuoe** [cl-library-docs/common-lisp-libraries#8]
Hey all - on the readme there's a link to https://github.com/cl-library-docs/common-lisp-libraries/blob/master/quicklisp/#getting-started, which is 404'ing on me.

I'm not sure where it was originally supposed to.
Thanks.

**Comment by digikar99** [comment]
Thanks for pointing out! I'll move this up some time

> (See the [html version of this page](https://common-lisp-libraries.readthedocs.io), rather than the markdown version for the working links below.)

And/or specifying absolute links on the home page with a better way to specify the base URL.

**Comment by Zulu-Inuoe** [comment]
I'm closing out this issue (feel free to reopen) since having the readme updated to reference the hosted version seems perfectly fine to me per 7117f1ce7082a74377173567048331a6f21e762a
